# Workflow setup for building Native iOS project
workflows:
    ios-project: # workflow ID
        name: iOS project # workflow name
        environment:
            xcode: latest
            cocoapods: default
        scripts:
             - name: Install CocoaPods dependencies
               script: | 
                    pod install
             - name: sonarqube
               script: | 
                     wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-macosx.zip
                     unzip sonar-scanner-cli-4.7.0.2747-macosx.zip
                     SONAR_TOKEN="798adff563c5a05aa04c32cb3453b77355cbb009"
                     sonar-scanner-4.7.0.2747-macosx/bin/sonar-scanner \
                      -Dsonar.organization=eurus \
                      -Dsonar.projectKey=sample_ios \
                      -Dsonar.sources=./swiftly \
                      -Dsonar.host.url=https://sonarcloud.io \
                      -Dsonar.login=$SONAR_TOKEN \
                      
             - name: build your app without sigining 
               script: | 
                     xcodebuild build -workspace "swiftly.xcworkspace" -scheme "swiftly" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
